### ISSUE TITLE
Deal with datacenters better

### ISSUE THREAD

**Issue by webcracy** [Gandi/docker-machine-gandi#2]
Better handle the datacenter flag:
- The `--gandi-datacenter` flag should accept DC codes instead of names (eg: `US-BA1` instead of `Level3 Baltimore`)
- Available datacenters should be listed in the README.

(originally reported by @jmbarbier)

**Comment by gdchamal** [comment]
@webcracy complete replace of datacenter name by dc_code, is it ok ? or should we deal with both values and make some magic ?

**Comment by webcracy** [comment]
@gdchamal dc_code only, IMHO. To be in line with the CLI. Save the mana for #3 :)

**Comment by gdchamal** [comment]
right I merge this for dc_code. Will trying to understand how it work in cli for user images and report change on related issue and then build a 0.2 release

**Comment by webcracy** [comment]
@gdchamal Cool, thx!

**Comment by gdchamal** [comment]
closed by PR #4
